language: "node_js"

node_js:
  - "8"
cache:
  directories:
  - "node_modules"

services:
  - mongodb

before_install:
  - yarn --version
  - webpack --version

install:
  - yarn install

script:
  - yarn run prod
